/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PaqueteA;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author djjav
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();

        //maximizar al abrir formulario
        this.setExtendedState(Principal.MAXIMIZED_BOTH);
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mdiPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCategorias = new javax.swing.JMenu();
        mnuAlimentos = new javax.swing.JMenuItem();
        mnuBelleza = new javax.swing.JMenuItem();
        mnuFerreteria = new javax.swing.JMenuItem();
        mnuJugueteria = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bodega de Mayoristas");

        javax.swing.GroupLayout mdiPrincipalLayout = new javax.swing.GroupLayout(mdiPrincipal);
        mdiPrincipal.setLayout(mdiPrincipalLayout);
        mdiPrincipalLayout.setHorizontalGroup(
            mdiPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
        );
        mdiPrincipalLayout.setVerticalGroup(
            mdiPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        mnuCategorias.setText("Categorias");

        mnuAlimentos.setText("Alimentos");
        mnuAlimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAlimentosActionPerformed(evt);
            }
        });
        mnuCategorias.add(mnuAlimentos);

        mnuBelleza.setText("Belleza");
        mnuBelleza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBellezaActionPerformed(evt);
            }
        });
        mnuCategorias.add(mnuBelleza);

        mnuFerreteria.setText("Ferrretería");
        mnuCategorias.add(mnuFerreteria);

        mnuJugueteria.setText("Juguetería");
        mnuCategorias.add(mnuJugueteria);

        jMenuBar1.add(mnuCategorias);

        mnuSalir.setText("Salir");
        mnuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mdiPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mdiPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_mnuSalirMouseClicked

    private void mnuAlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAlimentosActionPerformed
        // TODO add your handling code here:
        FrmAlimentos formularioInterno = new FrmAlimentos();
        mdiPrincipal.add(formularioInterno);
        Dimension containerSize = mdiPrincipal.getSize();
        Dimension formSize = formularioInterno.getSize();
        
        formularioInterno.setLocation(((int)containerSize.getWidth() - (int)formSize.getWidth())/2,
        ((int)containerSize.getHeight()-(int)formSize.getHeight())/2);
        
        formularioInterno.show();
    }//GEN-LAST:event_mnuAlimentosActionPerformed

    private void mnuBellezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBellezaActionPerformed
        frmBelleza products = new frmBelleza();
        mdiPrincipal.add(products);
        //the size of the mdi
        Dimension size = mdiPrincipal.getSize();
        //the size of the frame by instance
        Dimension formSize = products.getSize();
        products.setLocation(((int) size.getWidth() - (int) formSize.getWidth()) / 2, ((int) size.getHeight() - (int) formSize.getHeight()) / 2);
        products.show();
    }//GEN-LAST:event_mnuBellezaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane mdiPrincipal;
    private javax.swing.JMenuItem mnuAlimentos;
    private javax.swing.JMenuItem mnuBelleza;
    private javax.swing.JMenu mnuCategorias;
    private javax.swing.JMenuItem mnuFerreteria;
    private javax.swing.JMenuItem mnuJugueteria;
    private javax.swing.JMenu mnuSalir;
    // End of variables declaration//GEN-END:variables


}
